[package]
name = "web"
version = "0.1.0"
edition = "2021"
authors = ["Akashic Zhang <2095138755@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = "4.4.11"
nickel = "0.11.0"
